AWSTemplateFormatVersion: '2010-09-09'
Description: 'FusionArt Data Stack: RDS MySQL and ElastiCache Redis'

Parameters:
  ProjectName:
    Type: String
    Default: FusionArt
  PrivateDataSubnet1:
    Type: String
  PrivateDataSubnet2:
    Type: String
  RDSSecurityGroupId:
    Type: String
  RedisSecurityGroupId:
    Type: String
  DBUser:
    Type: String
    Default: admin
  DBPassword:
    Type: String
    NoEcho: true
  DBName:
    Type: String
    Default: ArtGallery

Resources:
  # RDS Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub ${ProjectName} RDS Subnet Group
      SubnetIds:
        - !Ref PrivateDataSubnet1
        - !Ref PrivateDataSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-DB-Subnet-Group

  # RDS MySQL Instance (Multi-AZ)
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: mysql
      EngineVersion: '8.0'
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroupId
      MultiAZ: false
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-RDS

  # Redis Subnet Group
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Sub ${ProjectName} Redis Subnet Group
      SubnetIds:
        - !Ref PrivateDataSubnet1
        - !Ref PrivateDataSubnet2

  # ElastiCache Redis Cluster
  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t3.micro
      Engine: redis
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - !Ref RedisSecurityGroupId
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-Redis

Outputs:
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub ${ProjectName}-RDSEndpoint
  RedisEndpoint:
    Value: !GetAtt RedisCluster.RedisEndpoint.Address
    Export:
      Name: !Sub ${ProjectName}-RedisEndpoint
