AWSTemplateFormatVersion: '2010-09-09'
Description: 'FusionArt Secrets Stack: Centralized Configuration'

Parameters:
  ProjectName:
    Type: String
  RDSEndpoint:
    Type: String
  DBUser:
    Type: String
  DBPassword:
    Type: String
  RedisEndpoint:
    Type: String
  QueueUrl:
    Type: String

Resources:
  AppSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref ProjectName
      Description: !Sub "Secrets for ${ProjectName} application"
      SecretString: !Sub |
        {
          "DB_URL": "jdbc:mysql://${RDSEndpoint}:3306/ArtGallery",
          "DB_USERNAME": "${DBUser}",
          "DB_PASSWORD": "${DBPassword}",
          "REDIS_HOST": "${RedisEndpoint}",
          "SQS_QUEUE_NOTIFICATIONS": "${QueueUrl}",
          "AWS_REGION": "${AWS::Region}",
          "RAZOR_PAY_KEY": "RazorPayKey_placeholder_change_in_console",
          "RAZOR_PAY_SECRET": "RazorPaySecret_placeholder_change_in_console",
          "EMAIL_USERNAME": "EmailUsername_placeholder_change_in_console",
          "EMAIL_PASSWORD": "EmailPassword_placeholder_change_in_console",
          "DDL_AUTO": "update",
          "SHOW_SQL": "false"
        }

Outputs:
  SecretArn:
    Value: !Ref AppSecret
    Export:
      Name: !Sub ${AWS::StackName}-SecretArn
