AWSTemplateFormatVersion: '2010-09-09'
Description: 'FusionArt Secrets Stack: Centralized Configuration'

Parameters:
  ProjectName:
    Type: String
  DBPassword:
    Type: String

Resources:
  AppSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref ProjectName
      Description: !Sub "Secrets for ${ProjectName} application"
      SecretString: !Sub |
        {
          "DB_PASSWORD": "${DBPassword}",
          "RAZOR_PAY_KEY": "rzp_test_STPlLg7Rq7gYlj",
          "RAZOR_PAY_SECRET": "asbxaIPLz6rpWmnqfBVto6I7",
          "EMAIL_USERNAME": "fusionart0101@gmail.com",
          "EMAIL_PASSWORD": "fnnm ujvy xgub opwq",
          "DDL_AUTO": "update",
          "SHOW_SQL": "false",
          "JWT_SECRET": "23ui42ydq78cebqnspduq8o2h47ybr807G@*&G)&*TBD87qdb87gw7gw7dxhsefgbouydewgfyeb8723brf87gv2bdy8eg3w2g6"
        }

Outputs:
  SecretArn:
    Value: !Ref AppSecret
    Export:
      Name: !Sub ${AWS::StackName}-SecretArn
