version: 0.0
os: linux
files:
  - source: ArtGalleryProject/backend/target/ArtGalleryProject-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app
  - source: ArtGalleryProject/scripts/
    destination: /home/ec2-user/scripts
hooks:
  BeforeInstall:
    - location: ArtGalleryProject/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ArtGalleryProject/scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: ArtGalleryProject/scripts/start_server.sh
      timeout: 600
      runas: ec2-user
