version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd $CODEBUILD_SRC_DIR/ArtGalleryProject/frontend && npm install --legacy-peer-deps
      - cd $CODEBUILD_SRC_DIR/ArtGalleryProject/backend && chmod +x mvnw
  build:
    commands:
      - echo "Building Frontend..."
      - cd $CODEBUILD_SRC_DIR/ArtGalleryProject/frontend && npm run build
      - echo "Building Backend..."
      - cd $CODEBUILD_SRC_DIR/ArtGalleryProject/backend && ./mvnw clean package -DskipTests
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - 'appspec.yml'
  secondary-artifacts:
    BackendArtifact:
      files:
        - 'ArtGalleryProject/backend/target/ArtGalleryProject-0.0.1-SNAPSHOT.jar'
        - 'appspec.yml'
        - 'ArtGalleryProject/scripts/**/*'
    FrontendArtifact:
      base-directory: 'ArtGalleryProject/frontend/dist'
      files:
        - '**/*'
