version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd ArtGalleryProject/frontend && npm install --legacy-peer-deps
      - cd ../backend && chmod +x mvnw
  build:
    commands:
      - echo Building Frontend...
      - cd ../frontend && npm run build
      - echo Building Backend...
      - cd ../backend && ./mvnw clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'ArtGalleryProject/backend/target/*.jar'
    - 'ArtGalleryProject/frontend/dist/**/*'
    - 'appspec.yml'
    - 'ArtGalleryProject/scripts/**/*'
  discard-paths: no
